<x-admin-layout>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, vel excepturi. Ea minus quas error dignissimos, nemo repellendus dolore illum quos veniam aut in ipsum beatae tempore doloremque maiores eveniet.</p>
    <p>Harum quibusdam vitae, neque eveniet corrupti impedit cumque quo nam rem maiores mollitia at, sapiente cum libero numquam recusandae modi animi! Esse itaque dolorem odit accusantium dolor laboriosam porro magni!</p>
    <p>Nobis porro repudiandae officia neque culpa maiores animi quos obcaecati quam mollitia! Similique minus voluptates impedit suscipit nobis qui aspernatur consequatur ex molestiae quam, sunt animi fuga repellat unde cumque?</p>
    <p>Repellat eveniet quisquam quam! Corporis sed eveniet sunt temporibus consequatur mollitia reprehenderit unde quod inventore voluptate. Hic voluptatem repellendus, optio quam, quod, architecto cum similique neque quaerat ratione ad. Saepe.</p>
    <p>Temporibus magnam soluta expedita inventore iste quod voluptatum. Vero voluptas aliquid nisi pariatur neque dolore animi molestiae aliquam consequatur eligendi sint iusto, cum, rem vel velit molestias porro. Tempora, deleniti!</p>
    <p>Porro molestiae iure enim maxime voluptas! Itaque provident quod explicabo incidunt sed iusto perspiciatis eligendi commodi molestiae tenetur facilis enim aperiam, quaerat velit? Cum, voluptates perferendis quia laborum nostrum deserunt.</p>
    <p>Earum culpa iste iure distinctio illo aut inventore officia corporis, repellendus eum eius fuga, facilis hic voluptatum soluta quae laboriosam ipsa, perspiciatis in. Labore molestias maxime sequi alias recusandae natus!</p>
    <p>Similique aperiam deserunt neque esse obcaecati iure numquam ipsam ea, corrupti quos temporibus excepturi molestiae perferendis perspiciatis odio. Alias recusandae, rem tempora doloribus incidunt fugiat repellat porro labore delectus maiores?</p>
    <p>Esse autem officiis error veritatis similique enim eaque, dicta tenetur rem quaerat fugiat, beatae obcaecati voluptatum inventore necessitatibus temporibus saepe deserunt vel iure? Accusamus, libero. Rerum sint modi expedita soluta!</p>
    <p>Quibusdam quos cumque illo quasi rerum tenetur odio, quam accusamus delectus voluptatum alias assumenda ipsa repellendus labore aspernatur ex distinctio modi nisi, totam beatae aperiam aliquid vero amet! Cum, libero?</p>
    <p>Soluta enim debitis eius. At ipsa sequi animi nostrum quaerat pariatur facere quisquam nemo minima debitis rerum harum necessitatibus a, enim sunt, magni ab ipsum vero accusantium? Ipsum, velit tempora.</p>
    <p>Porro neque dolores aspernatur corrupti, cumque earum molestiae rerum id voluptatem qui, dignissimos rem omnis, magni mollitia quibusdam! Eligendi ducimus magnam libero repudiandae praesentium numquam porro! Iusto temporibus explicabo et.</p>
    <p>Minima consequatur, dolores laudantium numquam placeat culpa atque dolore similique accusamus voluptas ipsa soluta repellat pariatur, illum distinctio! Laborum enim rerum nam non cupiditate, incidunt aliquid asperiores ab delectus error?</p>
    <p>Nemo animi at id, voluptatum est minima aperiam repudiandae asperiores, molestiae blanditiis aliquam necessitatibus nobis quod debitis temporibus nulla atque culpa quibusdam deleniti cum totam velit corrupti cupiditate voluptatem! Praesentium!</p>
    <p>Deleniti praesentium nam a amet architecto magni sint magnam harum. Hic voluptatum iste laboriosam ex nulla delectus beatae cupiditate magni nesciunt. Voluptatem esse, exercitationem quod odit nobis provident quo sunt.</p>
    <p>Culpa qui itaque molestias, hic voluptatem animi repellendus saepe cupiditate velit inventore fugit magni quidem unde excepturi id quasi asperiores recusandae fugiat ratione ad obcaecati vero cum. Eveniet, hic! Unde.</p>
    <p>Recusandae iusto numquam, doloremque perferendis eum libero ducimus non neque necessitatibus adipisci repellendus esse pariatur quidem sunt quasi facere nostrum quas. Enim, consectetur. In, maiores deserunt. Ullam beatae consectetur sint.</p>
    <p>Dolorem id in nulla nobis quidem ipsum necessitatibus saepe voluptates, est sequi odit eveniet expedita, porro distinctio doloremque molestiae cupiditate! Hic laborum totam modi inventore. Magni, debitis quasi! Nostrum, nesciunt.</p>
    <p>Voluptatum, nobis officiis nulla odit laudantium blanditiis dolorem expedita voluptatibus odio animi excepturi aliquam magni, doloribus a veritatis nisi quas deleniti vel error quo? Quasi minima laudantium fugiat labore ex.</p>
    <p>Nostrum possimus iure cum officia delectus repudiandae dolorum, odit sed, quas iste magni, ut obcaecati quo placeat voluptatum? Quisquam magnam blanditiis maiores quibusdam suscipit. Voluptatem corporis dolor veniam vitae at.</p>
</x-admin-layout>